instafetcher/instafetch/urls.py
from django.urls import path
from . import views

app_name = "instafetch"

urlpatterns = [
    path('', views.login, name="home"),
    path('index', views.index, name="index"),
    path('login', views.login, name="login"),
    path('signup', views.signup, name="signup"),
    path('addUser', views.addUser, name="addUser"),
    path('addPage', views.addPage, name="addPage"),
    path('fetch', views.fetch, name="fetch"),
    path('deletePage', views.deletePage, name="deletePage"),
    path('Success', views.success, name="success"),
]

instafetcher/instafetcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('instafetch/', include('instafetch.urls')),
    path('admin/', admin.site.urls),
]

instafetcher/instafetch/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.email

class Page(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)

    def __str__(self):
        return self.username

class Login(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    secretPassword = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.email

instafetcher/instafetch/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from instaloader import ProfileNotExistsException
from django.urls import reverse
import re


from .models import User, Page, Login
import instaloader
import datetime
import yagmail

regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'

# Create your views here.
def index(request):
    try:  # get email and password post data
        email = request.POST['email']
        password = request.POST['password']
        context = {'email': email}
    except:  # no email and/or password post data received
        context = {'error_message': 'No password/email post data received'}
        return render(request, 'instafetch/login.html', context)

    try:  # get the user object
        userObj = User.objects.get(email=email)
    except:
        context = {'error_message': f'No such user {email} exists'}
        return render(request, 'instafetch/login.html', context)


    if(not userObj.password == password):  # email and password don't match
        context = {'error_message': f'Incorrect password for user {email}'}
        return render(request, 'instafetch/login.html', context)
    else:
        context['linked_page_list'] = Page.objects.filter(user=userObj)

        return render(request, 'instafetch/index.html', context)


def login(request):
    return render(request, 'instafetch/login.html')

def addUser(request):
    if request.method=="POST":
        user = User()
        email = request.POST.get('email')
        if check(email) == 1:
            user.email = email
            user.password = request.POST.get('password')
            user.save()
            return HttpResponseRedirect(reverse('instafetch:login'))
        else:
            context = {'error_message': f'not a valid email please try again'}
            return render(request, 'instafetch/signup.html', context)
    else:
        return render(request, 'instafetch/signup.html')

def signup(request):
    return render(request, 'instafetch/signup.html')

def addPage(request):
    try:  # get email post data
        email = request.POST['email']
    except:
        context = {'error_message': 'No email post data received'}
        return render(request, 'instafetch/error.html', context)

    try:
        userObj = User.objects.get(email=email)
    except:
        context = {'error_message': 'No email post data received'}
        return render(request, 'instafetch/error.html', context)
    try:
        L = instaloader.Instaloader()
        loginInfo = Login.objects.get()
        L.login(loginInfo.email, loginInfo.password)
        username = request.POST["username"]
        profile = instaloader.Profile.from_username(L.context, username)

    except ProfileNotExistsException:
        context = {'error_message': f"The account {username} does not exist."}
        return render(request, 'instafetch/error.html', context)

    #  add the page to the database
    page = Page()
    page.username = username
    page.user = userObj
    page.save()

    return HttpResponseRedirect(reverse('instafetch:success'))


def fetch(request):
    ## send email
    superSecret = Login.objects.get()
    yag = yagmail.SMTP("instafetch457@gmail.com", superSecret.secretPassword)
    users = User.objects.all()

    for user in users:

        print(user)
        content = """
        <h1>Here is your instafetch update</h1>
        """
        for page in user.page_set.all():
            print(page)
            if page is None:
                break
            else:
                posts = getImages(page.username)
                content += f'<h3 style="text-align:center;">Here is the update on {page}</h3>'
                for path in posts:
                    print(path)
                    if path is None:
                        break
                    else:
                        content += f'<img src="{path}" style="width: 50%; display: block; margin: auto;">'
                        content += f'<p style="text-align: center;">{posts[path]}</p>'
                        content += "<hr>"

        yag.send(to=user.email, subject='Your instafetch update', contents=content)
    return render(request, "instafetch/login.html")

def fetch2(request):
    ## send email
    yag = yagmail.SMTP("instafetch457@gmail.com", "upsiavvbnqfxcudl")
    posts = getImages("shitheadsteve")
    content = """
    <h1>Hello there</h1>
    """
    for path in posts:
        content += f'<img src="{path}">'
        content += posts[path]

    yag.send(to='instafetch457@gmail.com', subject='Your instafetch update', contents=content)
    return render(request, "instafetch/login.html")


def getImages(username):
    L = instaloader.Instaloader()
    loginInfo=Login.objects.get()
    print(loginInfo.username)
    print (loginInfo.password)
    L.login(loginInfo.username, loginInfo.password)
    try:
        profile = instaloader.Profile.from_username(L.context, username)

    except instaloader.ProfileNotExistsException:
        print(f"The account {username} does not exist.")

    recent_posts = {}
    now = datetime.datetime.now()
    one_hour_ago = now - datetime.timedelta(hours=12)
    for post in profile.get_posts():
        if post.date > one_hour_ago:
            recent_posts[post.url] = post.caption
        else:
            break
    return recent_posts

def deletePage(request):
    if request.method == "POST":
        page_id = request.POST.get('page_id')
        email = request.POST['email']
        context = {'email': email}
        try:  # get the user object
            userObj = User.objects.get(email=email)
        except:
            context = {'error_message': f'No such user {email} exists'}
            return redirect(request, 'instafetch/login.html', context)
    Page.objects.filter(id=page_id).delete()
    context['linked_page_list'] = Page.objects.filter(user=userObj)
    return render(request, 'instafetch/index.html', context)
    # previous_url = request.META.get('HTTP_REFERER', None)
    # if previous_url:
    #     return redirect(previous_url)
    # else:
    #     return redirect(reverse('instafetch:index'))

def success(request):
    return render(request, 'instafetch/Success.html')


def check(email):
    # pass the regular expression
    # and the string into the fullmatch() method
    if(re.fullmatch(regex, email)):
        return 1

    else:
        return 0

instafetcher/instafetch/templates/instafetch/Success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'instafetch/loginstyle.css' %}">
    <meta charset="UTF-8">
    <title>Successful add</title>
</head>
<body>
<h1 class="instaheader">InstaFetcher</h1>
<h2 class="center">Successfully add the page to your account!</h2>
<p>Click  <a href="{% url 'instafetch:login' %}">here</a> to log out</p>

</body>
</html>

instafetcher/instafetch/templates/instafetch/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
<p>There was an error</p>
</body>
</html>

instafetcher/instafetch/templates/instafetch/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link rel="stylesheet" href="{% static 'instafetch/loginstyle.css' %}">
        <meta charset="utf-8">
        <title>InstaFetch</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    </head>
<body>
    <h1 class="instaheader">InstaFetcher</h1>
    <h2 class="center">Welcome to InstaFetcher</h2>
    <div class="center">
        <div class="center, container">
            <form method="post" action="{% url 'instafetch:addPage' %}">
                {% csrf_token %}
                {% if error_message %}<p class="red"><strong>{{ error_message }}</strong></p>
                {% endif %}
                <h2>Add page to notification list</h2>

                <div class="input-parent">
                    <label for="username">Username</label>
                    <input name="username" type="text" id="username">

                    <input type="hidden" name="email" value="{{ email }}">
                </div>
                <button type="submit">Add page</button>
            </form>
        </div>
        <div class="container">
            <h4 class="center">Lists of linked pages</h4>
            {%if linked_page_list%}
            {%for page in linked_page_list%}
            <div>
                Page: {{page.username}}
                <form method="post" action="{% url 'instafetch:deletePage' %}">
                    {% csrf_token %}
                    <input type="hidden" name="page_id" value="{{ page.id }}">
                    <input type="hidden" name="email" value="{{ email }}">
                    <button type="submit">Delete</button>
                </form>
            </div>
            {%endfor%}
            {% else %}
            <p>No linked pages</p>
            {%endif%}
        </div>
    </div>
</body>
</html>

instafetcher/instafetch/templates/instafetch/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link rel="stylesheet" href="{% static 'instafetch/loginstyle.css' %}">
        <meta charset="utf-8">
        <title>Instafetch login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    </head>
    <body>
    <h1 class="instaheader">InstaFetcher</h1>
    <div class="center, container">
            <form method="post" action="{% url 'instafetch:index' %}">
                {% csrf_token %}
                {% if error_message %}<p class="red"><strong>{{ error_message }}</strong></p>
                {% endif %}
                <h2>Login to your account</h2>

                <div class="input-parent">
                    <label for="email">Email</label>
                    <input name="email" type="email" id="email">
                </div>

                <div class="input-parent">
                    <label for="password">Password</label>
                    <input name="password" type="password" id="password">
                </div>

                <button type="submit">Login</button>
            </form>
        <p> Don't have an account?</p>
        <p> Sign up <a href="{% url 'instafetch:signup' %}">here</a></p>
    </div>
    </body>
</html>

instafetcher/instafetch/templates/instafetch/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link rel="stylesheet" href="{% static 'instafetch/loginstyle.css' %}">
        <meta charset="utf-8">
        <title>Instafetch login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    </head>
    <body>
    <h1 class="instaheader">InstaFetcher</h1>
    <div class="center, container">
        <form method="post" action="{% url 'instafetch:addUser' %}">
            {% csrf_token %}
            {% if error_message %}<p class="red"><strong>{{ error_message }}</strong></p>
            {% endif %}
            <h2>create your account</h2>

            <div class="input-parent">
                <label for="email">Email</label>
                <input name="email" type="email" id="email">
            </div>

            <div class="input-parent">
                <label for="password">Password</label>
                <input name="password" type="password" id="password">
            </div>

            <button type="submit">create account</button>
        </form>
        <p> Already have an account?</p>
        <p> Sign in <a href="{% url 'instafetch:login' %}">here</a></p>
    </div>
    </body>
</html>